# Generated by Django 3.2.4 on 2022-05-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
