# Generated by Django 3.2.4 on 2021-08-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210718_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contents', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'code']},
        ),
    ]
