# Generated by Django 3.2.4 on 2021-08-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210824_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'journal entries'},
        ),
    ]
