# Generated by Django 3.2.4 on 2021-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_journalentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='contents',
            field=models.TextField(),
        ),
    ]
