# Generated by Django 3.2.4 on 2022-09-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_book_year_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'journal entries'},
        ),
    ]
